[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python =  "^3.11"
pre-commit = "^4.1.0"
pre-commit-hooks = "^5.0.0"
mdformat = "^0.7.22"
mdformat-gfm = "^0.4.1"
mdformat-gfm-alerts = "^1.0.1"
yamllint = "^1.35.1"
zizmor = "^1.3.0"
