# For setting repository-specific setting, see the Zizmor
# configuration settings:
# https://woodruffw.github.io/zizmor/configuration/
---
name: Lint Github Actions

on:
  workflow_call:
    inputs:
      path:
        description: >-
         Path to the directory or workflow file to lint. Defaults to the root
         of the repo which will detect the default Actions workflow location
         at '.github/workflows/'
        type: string
        default: "."

      # Zizmor has no dependencies so there's no need to use a lockfile
      zizmor-version:
        description: Version of Zizmor to install
        type: string
        default: "1.5.1"

      zizmor-options:
        description: Additional CLI options to pass to the Zizmor command.
        type: string
        default: "--min-severity=medium"

env:
  PYTHON_VERSION: "3.12"

permissions:
  contents: read
  actions: read

jobs:
  lint-actions:
    name: Lint:Actions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install zizmor
      run: python -m pip install "zizmor==$ZIZMOR_VERSION"
      env:
        ZIZMOR_VERSION: ${{ inputs.zizmor-version }}

    - name: Lint
      run: zizmor "$ZIZMOR_PATH" $ZIZMOR_OPTIONS
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ZIZMOR_PATH: ${{ inputs.path }}
        ZIZMOR_OPTIONS: ${{ inputs.zizmor-options }}
