---

name: FPF/Signed-Commit-GPG
description: Create a GPG-signed commit modifying one or more files

inputs:
  create_branch:
    description: "If set, the action will create/switch to this branch before committing"
    required: false
    default: ""

  files:
    description: List of files to stage & commit
    required: true

  message:
    description: Commit message
    required: false
    default: "Automatic commit"

  repo:
    description: Repository to commit to in owner/name format; defaults to current repo
    required: false
    default: ""

  repo-path:
    description: Path to the local clone of the repository
    required: false
    default: "."

outputs:
  commit-sha:
    description: SHA of the created commit
    value: ${{ steps.commit.outputs.sha }}
  commit-url:
    description: URL of the commit on GitHub
    value: https://github.com/${{ inputs.repo || github.repository }}/commit/${{ steps.commit.outputs.sha }}

runs:
  using: composite
  steps:

    - name: Import PGP key
      id: import-gpg
      shell: bash
      env:
        PGP_KEY_B64: ${{ secrets.FPF_BRANCH_UPDATER_PGP_KEY }}
      run: |
        if [[ -z "$PGP_KEY_B64" ]]; then
          echo "Missing required secret: FPF_BRANCH_UPDATER_PGP_KEY"
          exit 1
        fi

        echo "$PGP_KEY_B64" | base64 --decode | gpg --import

        KEY_ID=$(
          gpg --list-secret-keys --keyid-format=long \
            | awk '/sec/ {print $2}' \
            | head -n1 \
            | cut -d'/' -f2
        )

        echo "key-id=$KEY_ID" >> "$GITHUB_OUTPUT"

    - name: Create or switch to branch
      if: ${{ inputs.create_branch != '' }}
      shell: bash
      working-directory: ${{ inputs.repo-path }}
      env:
        BRANCH: ${{ inputs.create_branch }}
      run: |
        echo "Switching to branch: $BRANCH"
        git fetch origin "$BRANCH" || true
        git checkout -B "$BRANCH" "origin/$BRANCH" || git checkout -B "$BRANCH"

    - name: Configure Git for signed commits
      shell: bash
      working-directory: ${{ inputs.repo-path }}
      env:
        GIT_EMAIL: ${{ vars.FPF_BRANCH_UPDATER_PGP_EMAIL }}
        GIT_NAME: ${{ vars.FPF_BRANCH_UPDATER_PGP_IDENTITY }}
        GPG_KEY_ID: ${{ steps.import-gpg.outputs.key-id }}
      run: |
        git config user.email "$GIT_EMAIL"
        git config user.name "$GIT_NAME"
        git config user.signingkey "$GPG_KEY_ID"
        git config commit.gpgsign true
        git config tag.gpgsign true

    - name: Commit changes
      id: commit
      shell: bash
      working-directory: ${{ inputs.repo-path }}
      env:
        FILES: ${{ inputs.files }}
        MSG: ${{ inputs.message }}
      run: |
        echo "$FILES" | while IFS= read -r f; do
          [[ -z "$f" ]] && continue
          git add "$f"
        done

        git commit -m "$MSG"

        SHA=$(git rev-parse HEAD)
        echo "sha=$SHA" >> "$GITHUB_OUTPUT"

    - name: Push to origin
      shell: bash
      working-directory: ${{ inputs.repo-path }}
      env:
        BRANCH: ${{ inputs.create_branch }}
      run: |
        if [[ -n "$BRANCH" ]]; then
          echo "Pushing new branch $BRANCH"
          git push --set-upstream origin "$BRANCH"
        else
          echo "Pushing current branch"
          git push
        fi
